default:
	#arm-linux-gnueabihf-g++ -g -D_DEBUG -O0 -o testD -L. -ltsiprec2D -lrt TestRec.cpp
	arm-linux-gnueabihf-g++ -o test -L. -ltsiprec2  -lrt TestRec.cpp

clean:
	rm -rf *.o
	rm -rf test
	rm -rf testD
