#ifndef __MY_ERROR_H_20110525__
#define __MY_ERROR_H_20110525__

enum
{
	S_OK = 0,
	ERROR_SUCCESS = 0,
	ERROR_NOT_SUPPORTED,
	ERROR_BAD_NET_NAME,
	ERROR_INVALID_DATA,
	ERROR_INSUFFICIENT_BUFFER,
	ERROR_BAD_ARGUMENTS,
	ERROR_INVALID_PARAMETER,
	ERROR_NOT_ENOUGH_MEMORY,
	ERROR_INSTALL_FAILURE,
	ERROR_GEN_FAILURE,
	ERROR_NOT_READY,



	E_ERROR_BASE = 100000,
	E_POINTER,
	E_NOINTERFACE,
};


#endif // __MY_ERRNO_H_20110525__

