copy dvb_crc.h ..\..\include\MyDVBPSI
copy TSPacketDemux.h ..\..\include\MyDVBPSI
copy dvbdescriptorsdefine.h ..\..\include\MyDVBPSI
copy dvbpsitablesdefine.h ..\..\include\MyDVBPSI
copy DVBPSITables.h ..\..\include\MyDVBPSI
copy DVBDescriptors.h ..\..\include\MyDVBPSI
copy tspacket.h ..\..\include\MyDVBPSI
copy PESPacket.h ..\..\include\MyDVBPSI
copy bitstream.h ..\..\include\MyDVBPSI
copy TSPacketEncapsulator.h ..\..\include\MyDVBPSI
copy PESPacketEncapsulator.h ..\..\include\MyDVBPSI
copy PSITableGenerator.h ..\..\include\MyDVBPSI
copy tsmpeg4bropmthelper.h ..\..\include\MyDVBPSI
copy dvbpsiscanprogramhelper.h ..\..\include\MyDVBPSI
copy TSVODPSI_TableGenerator.h ..\..\include\MyDVBPSI
copy dvbpredefinetspids.h ..\..\include\MyDVBPSI
copy dvbpsieitgenerator.h ..\..\include\MyDVBPSI
copy mydvbteletextpage.h ..\..\include\MyDVBPSI
copy dvbpsitable_ip_mpe.h  ..\..\include\MyDVBPSI
copy dvbpsi_ip_mpe_generator.h  ..\..\include\MyDVBPSI
copy tsvodpsi_remotectrltblgenerator.h ..\..\include\MyDVBPSI