#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
/bin/echo > /dev/mdev.seq

echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s

insmod /ts/libcomposite.ko 
insmod /ts/usb_f_mass_storage.ko 
insmod /ts/g_mass_storage.ko file=/dev/mmcblk0p1 stall=0 removble=1

for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

lighttpd start -f /sbin/lighttpd.conf

TS_DTMB_Control 738
/ts/bluenet 0xb3-5053 0xb4-5054 &
/ts/test 5053 &



